{{- if .Values.serviceAccount.create -}}
apiVersion: v2
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- end -}}