server:
  port: 8080

rabbitmq:
  v-host: ${vHost}
  queue-name: ${queueName}

spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: ${rabbitmq-user}
    password: ${rabbitmq-password}
  kafka:
    producer:
      acks: all
      bootstrap-servers:
        - localhost:9092
      key-serializer:
        - org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        - org.apache.kafka.common.serialization.StringSerializer